routes/web.php
        'as' => 'admin'
    ])->middleware('can:manage-shipping-providers');
    // them ngay 15-07-2021
    Route::resource('shipping-method-providers', 'Admin\ShippingMethodProviderController', [
        'except' => ['show'],
        'parameters' => [
            'shipping-method-providers' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-shipping-providers');
    // het them ngay 15-07-2021
    Route::resource('payment-methods', 'Admin\PaymentMethodController', [
        'except' => ['show'],
        'parameters' => [
            'payment-methods' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-payment-methods');

    Route::get('/vnptconfirm', 'Admin\Vnptconfirm@index')->name('admin.vnptconfirm.index');
    Route::post('/vnptconfirm', 'Admin\Vnptconfirm@store')->name('admin.vnptconfirm');
    Route::post('/extent/approve', 'Admin\ExtentController@approve');
    Route::post('/extent/payment', 'Admin\ExtentController@payment');
    Route::post('/extent/cancel', 'Admin\ExtentController@cancel');
    Route::get('/extent', 'Admin\ExtentController@index')->name('admin.extent.index');
    Route::get('/extent/exportExcel', 'Admin\ExtentController@exportExcel')->name('admin.extent.exportExcel');
    Route::get('/extrafee/{orderid}/list', 'Admin\ExtentController@extrafee')->name('admin.extent.extrafee');

    Route::resource('extent', 'Admin\ExtentController', [
        'except' => ['show'],
        'parameters' => [
            'extent' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-extent');

    Route::get('/claim/view/{id}', 'Admin\ClaimController@view')->name('admin.claim.view');
    Route::post('/claim/create-conversation', 'Admin\ClaimController@createConversation');
    Route::post('/claim/complete', 'Admin\ClaimController@complete');
    Route::get('/claim/contact', 'Admin\ClaimController@contact')->name('admin.claim.contact');
    Route::get('/claim/contact/{id}/delete', 'Admin\ClaimController@delete')->name('admin.claim.delete');
    Route::resource('claim', 'Admin\ClaimController', [
        'except' => ['show'],
        'parameters' => [
            'claim' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-claim');

    Route::get('/receipts/excel', 'Admin\ReceiptController@exportExcel')->name('admin.receipts.excel');
    Route::resource('receipts', 'Admin\ReceiptController', [
        'except' => ['show'],
        'parameters' => [
            'receipts' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts');

    Route::post('/receipt-orders/add-items', 'Admin\ReceiptOrdersController@addItems')->name('admin.receipt-orders.add-items');
    Route::post('/receipt-orders/remove-item', 'Admin\ReceiptOrdersController@removeItem')->name('admin.receipt-orders.remove-item');
    Route::post('/receipt-orders/paid-voucher', 'Admin\ReceiptOrdersController@paidVoucher')->name('admin.receipt-orders.paid-voucher');
    Route::get('/receipt-orders/excel-item/{id}', 'Admin\ReceiptOrdersController@exportExcelItem')->name('admin.receipt-orders.excel-item');
    Route::get('/receipt-orders/excel', 'Admin\ReceiptOrdersController@exportExcel')->name('admin.receipt-orders.excel');
    Route::get('/receipt-orders/{id}/print', 'Admin\ReceiptOrdersController@printItem')->name('admin.receipt-orders.print-item');
    Route::resource('receipt-orders', 'Admin\ReceiptOrdersController', [
        'except' => ['show'],
        'parameters' => [
            'receipt-orders' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts-order');

    Route::post('/receipt-mts/add-items', 'Admin\ReceiptMtsController@addItems')->name('admin.receipt-mts.add-items');
    Route::post('/receipt-mts/remove-item', 'Admin\ReceiptMtsController@removeItem')->name('admin.receipt-mts.remove-item');
    Route::post('/receipt-mts/paid-voucher', 'Admin\ReceiptMtsController@paidVoucher')->name('admin.receipt-mts.paid-voucher');
    Route::get('/receipt-mts/excel-item/{id}', 'Admin\ReceiptMtsController@exportExcelItem')->name('admin.receipt-mts.excel-item');
    Route::get('/receipt-mts/excel', 'Admin\ReceiptMtsController@exportExcel')->name('admin.receipt-mts.excel');
    Route::get('/receipt-mts/{id}/print', 'Admin\ReceiptMtsController@printItem')->name('admin.receipt-mts.print-item');
    Route::resource('receipt-mts', 'Admin\ReceiptMtsController', [
        'except' => ['show'],
        'parameters' => [
            'receipt-mts' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts-mts');

    Route::post('/receipt-extra/add-items', 'Admin\ReceiptExtraController@addItems')->name('admin.receipt-extra.add-items');
    Route::post('/receipt-extra/remove-item', 'Admin\ReceiptExtraController@removeItem')->name('admin.receipt-extra.remove-item');
    Route::post('/receipt-extra/paid-voucher', 'Admin\ReceiptExtraController@paidVoucher')->name('admin.receipt-extra.paid-voucher');
    Route::get('/receipt-extra/excel-item/{id}', 'Admin\ReceiptExtraController@exportExcelItem')->name('admin.receipt-extra.excel-item');
    Route::get('/receipt-extra/excel', 'Admin\ReceiptExtraController@exportExcel')->name('admin.receipt-extra.excel');
    Route::get('/receipt-extra/{id}/print', 'Admin\ReceiptExtraController@printItem')->name('admin.receipt-extra.print-item');
    Route::resource('receipt-extra', 'Admin\ReceiptExtraController', [
        'except' => ['show'],
        'parameters' => [
            'receipt-extra' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts-extra');

    Route::resource('customer-groups', 'Admin\CustomerGroupsController', [
        'except' => ['show'],
        'parameters' => [
            'customer-groups' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-customer-groups');

    Route::get('/customers/points', 'Admin\CustomersController@points')->name('admin.customers.points');
    Route::get('/customers/coupons', 'Admin\CustomersController@coupons')->name('admin.customers.coupons');
    Route::get('/customers/search', 'Admin\CustomersController@search');
    Route::get('/customers/{id}/vip', 'Admin\CustomersController@vip')->name('admin.customers.getvip');
    Route::put('/customers/{id}/vip', 'Admin\CustomersController@updateVip')->name('admin.customers.vip');
    Route::get('/customers/{id}/point', 'Admin\CustomersController@point')->name('admin.customers.point');
    Route::get('/customers/excel', 'Admin\CustomersController@exportExcel')->name('admin.customers.excel');
    Route::get('/customers/{id}/address', 'Admin\CustomersController@address')->name('admin.customers.address');
    Route::delete('/customers/{id}/address-destroy', 'Admin\CustomersController@addressDestroy')->name('admin.customers.address_destroy');
    Route::get('/customers/{id}/address-edit', 'Admin\CustomersController@addressEdit')->name('admin.customers.address_edit');
    Route::put('/customers/{id}/address-update', 'Admin\CustomersController@addressUpdate')->name('admin.customers.address_update');
    Route::put('/customers/{id}/lock', 'Admin\CustomersController@lock')->name('admin.customers.lock');
    Route::put('/customers/{id}/unlock', 'Admin\CustomersController@unlock')->name('admin.customers.unlock');
    Route::resource('customers', 'Admin\CustomersController', [
        'except' => ['show'],
        'parameters' => [
            'customers' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-customers');

    Route::resource('campaign', 'Admin\CampaignController', [
        'except' => ['show'],
        'parameters' => [
            'campaign' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-campaign');

    Route::resource('logs', 'Admin\LogsController', [
        'except' => ['show'],
        'parameters' => [
            'logs' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-logs');

    Route::get('/roles/{id}/permissions', 'Admin\RolesController@getPermissions')->name('admin.roles.permissions');
    Route::put('/roles/{id}/permissions', 'Admin\RolesController@updatePermissions');
    Route::resource('roles', 'Admin\RolesController', [
        'except' => ['show'],
        'parameters' => [
            'roles' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-roles');

    Route::get('/agencies/{id}/products', 'Admin\AgenciesController@getProducts')->name('admin.agencies.products');
    Route::put('/agencies/{id}/products', 'Admin\AgenciesController@updateProductsPrice');
    Route::resource('agencies', 'Admin\AgenciesController', [
        'except' => ['show'],
        'parameters' => [
            'agencies' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-agencies');

    Route::resource('users', 'Admin\UsersController', [
        'except' => ['show'],
        'parameters' => [
            'users' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-users');

    Route::get('/configs', 'Admin\ConfigsController@index')->name('admin.configs.index');
    Route::get('/phpinfo', 'Admin\ConfigsController@phpinfo')->name('admin.phpinfo');
    Route::put('/configs', 'Admin\ConfigsController@update')->name('admin.configs.update');

    Route::get('/currencies/{id}/rate', 'Admin\CurrenciesController@rate')->name('admin.currencies.rate');
    Route::resource('currencies', 'Admin\CurrenciesController', [
        'except' => ['show'],
        'parameters' => [
            'currencies' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-currencies');

    Route::resource('product-groups', 'Admin\ProductGroupsController', [
        'except' => ['show'],
        'parameters' => [
            'product-groups' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-product-groups');
});

Auth::routes();

app/CustomerGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CustomerGroup extends Model
{
    /**
     * Table to use
     */
    protected $table = 'customer_groups';

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'code',
        'name',
        'description'
    ];

    /**
     * Has many Customer
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function customers()
    {
        return $this->hasMany(Customer::class, 'customer_group_id', 'id');
    }
}

app/Http/Controllers/Admin/CustomerGroupsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\CustomerGroup;
use Illuminate\Support\Facades\DB;
use Exception;
use App\Services\LogService;

class CustomerGroupsController extends Controller
{
    /**
     * Assign data
     */
    private $data;

    /**
     * CustomerGroupsController constructor.
     */
    public function __construct()
    {
        $this->data = [
            'menu' => '3.1'
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['groups'] = CustomerGroup::orderBy('code')->get();

        return view('admin.customer-groups.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.customer-groups.create', $this->data);
    }

    /**
     * Validate request
     *
     * @param Request $request
     * @param null $id
     */
    private function validateRequest(Request $request, $id = null)
    {
        $this->validate($request, [
            'code'        => 'required|string|max:20|unique:customer_groups,code' . ($id ? (',' . $id . ',id') : ''),
            'name'        => 'required|string|max:100',
            'description' => 'nullable|string'
        ], [], [
            'code'        => __('customer-group.code'),
            'name'        => __('customer-group.name'),
            'description' => __('customer-group.description')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateRequest($request);

        try {
            DB::beginTransaction();

            CustomerGroup::create($request->all());

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            LogService::error($e);
            abort(500);
        }

        return redirect()->route('admin.customer-groups.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!$group = CustomerGroup::find($id)) {
            abort(404);
        }
        $this->data['group'] = $group;

        return view('admin.customer-groups.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!$group = CustomerGroup::find($id)) {
            abort(404);
        }

        $this->validateRequest($request, $group->id);

        try {
            DB::beginTransaction();

            $group->update($request->all());

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            LogService::error($e);
            abort(500);
        }

        return redirect()->route('admin.customer-groups.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        if (!$group = CustomerGroup::find($id)) {
            abort(404);
        }

        try {
            DB::beginTransaction();

            $group->delete();

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            LogService::error($e);
            abort(500);
        }

        return redirect()->route('admin.customer-groups.index');
    }
}

resources/views/admin/customer-groups/create.blade.php
@extends('layouts.admin.index', ['menu' => $menu])

@section('body')
  <div class="panel panel-default">
    <div class="panel-heading">
      {{ __('customer-group.create') }}
    </div>
    <div class="panel-body">
      <form action="{{ route('admin.customer-groups.store') }}" method="post" role="form" class="form-horizontal">
        <div class="row">
          <div class="col-sm-6">
            @php $field = 'code'; @endphp
            <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
              <label for="{{ $field }}" class="control-label col-sm-3">
                {{ __('customer-group.code') }}<i class="text-danger">*</i>
              </label>
              <div class="col-sm-9">
                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field) }}">
                @if($errors->has($field))
                  <span class="validate-has-error">{{ $errors->first($field) }}</span>
                @endif
              </div>
            </div>

            @php $field = 'name'; @endphp
            <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
              <label for="{{ $field }}" class="control-label col-sm-3">
                {{ __('customer-group.name') }}<i class="text-danger">*</i>
              </label>
              <div class="col-sm-9">
                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field) }}">
                @if($errors->has($field))
                  <span class="validate-has-error">{{ $errors->first($field) }}</span>
                @endif
              </div>
            </div>
          </div>

          <div class="col-sm-6">
            @php $field = 'description'; @endphp
            <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
              <label for="{{ $field }}" class="control-label col-sm-3">
                {{ __('customer-group.description') }}
              </label>
              <div class="col-sm-9">
                <textarea name="{{ $field }}" id="{{ $field }}" cols="30" rows="2" class="form-control">{{ old($field) }}</textarea>
                @if($errors->has($field))
                  <span class="validate-has-error">{{ $errors->first($field) }}</span>
                @endif
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-12 text-right">
                <a href="{{ route('admin.customer-groups.index') }}" class="btn btn-white">
                  {{ __('label.cancel') }}
                </a>
                <button type="submit" class="btn btn-info disabled-submit">
                  <i class="fa fa-check"></i> {{ __('label.save) }}
                </button>
              </div>
            </div>
          </div>
        </div>
        {{ csrf_field() }}
      </form>
    </div>
  </div>
@endsection

resources/views/admin/customer-groups/edit.blade.php
@extends('layouts.admin.index', ['menu' => $menu])

@section('body')
    <div class="panel panel-default">
        <div class="panel-heading">
            {{ __('customer-group.edit') }}
        </div>
        <div class="panel-body">
            <form action="{{ route('admin.customer-groups.update', $group->id) }}" method="post" role="form" class="form-horizontal">
                <div class="row">
                    <div class="col-sm-6">
                        @php $field = 'code'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('customer-group.code') }}<i class="text-danger">*</i>
                            </label>
                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field, $group->{$field}) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>

                        @php $field = 'name'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('customer-group.name') }}<i class="text-danger">*</i>
                            </label>
                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field, $group->{$field}) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        @php $field = 'description'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('customer-group.description') }}
                            </label>
                            <div class="col-sm-9">
                                <textarea name="{{ $field }}" id="{{ $field }}" cols="30" rows="2" class="form-control">{{ old($field, $group->{$field}) }}</textarea>
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-12 text-right">
                                <a href="{{ route('admin.customer-groups.index') }}" class="btn btn-white">
                                    {{ __('label.cancel') }}
                                </a>
                                <button type="submit" class="btn btn-info disabled-submit">
                                    <i class="fa fa-check"></i> {{ __('label.update') }}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                {{ method_field('PUT') }}
                {{ csrf_field() }}
            </form>
        </div>
    </div>
@endsection

resources/views/admin/customer-groups/index.blade.php
@extends('layouts.admin.index', ['menu' => $menu])

@section('body')
  <div class="panel panel-default">
    <div class="panel-heading">
      {{ __('customer-group.manage') }}
    </div>
    <div class="panel-body">
      <div class="row form-group">
        <div class="col-sm-1">
          <a href="{{ route('admin.customer-groups.create') }}" class="btn btn-success">
            <i class="fa fa-plus-circle"></i> {{ __('label.add') }}
          </a>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>{{ __('customer-group.code') }}</th>
            <th>{{ __('customer-group.name') }}</th>
            <th width="30%">{{ __('customer-group.description') }}</th>
            <th>{{ __('label.action') }}</th>
          </tr>
          </thead>
          <tbody>
          @if($groups->count() > 0)
            @foreach($groups as $group)
              <tr>
                <td>{{ $group->code }}</td>
                <td>{{ $group->name }}</td>
                <td>{!! nl2br(e($group->description)) !!}</td>
                <td>
                  <a href="{{ route('admin.customer-groups.edit', $group->id) }}" class="btn btn-xs btn-warning">
                    <i class="fa fa-edit"></i>
                  </a>
                  <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal-delete-{{ $group->id }}">
                    <i class="fas fa-trash"></i>
                  </button>
                  <div class="modal fade" id="modal-delete-{{ $group->id }}">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <form action="{{ route('admin.customer-groups.destroy', $group->id) }}" method="post">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">{{ __('label.confirm_delete') }}</h4>
                          </div>
                          <div class="modal-body">
                            {!! __('label.confirm_delete_msg') !!}
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-white" data-dismiss="modal">{{ __('label.cancel') }}</button>
                            <button type="submit" class="btn btn-danger disabled-submit">
                              <i class="fas fa-trash"></i> {{ __('label.delete') }}
                            </button>
                          </div>
                          {{ csrf_field() }}
                          {{ method_field('delete') }}
                        </form>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            @endforeach
          @else
            <tr>
              <td colspan="4">{{ __('label.no_records') }}</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection