routes/web.php
    Route::get('/', 'YhlController@index')->name('yhl.frontend.index');
});

Route::group(['prefix' => 'mts', 'middleware' => 'auth'], function () {
    Route::get('/', 'MtsController@index')->name('mts.frontend.index');
    Route::get('/create', 'MtsController@create')->name('mts.frontend.create');
    Route::post('/store', 'MtsController@store');
    Route::get('/{id}', 'MtsController@show')->name('mts.frontend.show');
    Route::put('/{id}/update', 'MtsController@update')->name('mts.frontend.update');
    Route::get('/{id}/edit', 'MtsController@edit')->name('mts.frontend.edit');
});

Route::group(['prefix' => 'profile', 'middleware' => 'auth'], function () {
    Route::get('/', 'CustomerController@index')->name('profile.index');
    Route::get('/change-password', 'CustomerController@changePassword')->name('profile.changepass');
    Route::get('/address', 'CustomerController@address')->name('profile.address');
    Route::get('/point', 'CustomerController@point')->name('profile.point');
    Route::get('/coupon', 'CustomerController@coupon')->name('profile.coupon');
    Route::get('/get-coupon-code', 'CustomerController@getCouponCode');
    Route::get('/{id}/address-edit', 'CustomerController@addressEdit')->name('profile.address_edit');
    Route::put('/{id}/address-update', 'CustomerController@addressUpdate')->name('profile.address_update');
    Route::get('/address-create', 'CustomerController@addressCreate')->name('profile.address_create');
    Route::put('/address-store', 'CustomerController@addressStore')->name('profile.address_store');
    Route::get('/{id}/address-destroy', 'CustomerController@addressDestroy')->name('profile.address_destroy');
    Route::post('/update', 'CustomerController@update')->name('profile.update');
    Route::post('/update-change-password', 'CustomerController@updateChangePassword')->name('profile.update_changepass');
});

Route::prefix('product')->group(function() {
    Route::get('/', 'ProductController@index')->name('product.index');
    Route::get('/category/{id}', 'ProductController@category')->name('product.category');
    Route::get('/detail/{name}/{id}', 'ProductController@detail')->name('product.detail');
});

Route::prefix('news')->group(function() {
    Route::get('/', 'NewsController@index')->name('news.index');
    Route::get('/{slug}', 'NewsController@detail')->name('news.detail');
});

Route::prefix('helps')->group(function() {
    Route::get('/', 'HelpsController@index')->name('helps.index');
    Route::get('/{slug}', 'HelpsController@detail')->name('helps.detail');
});

Route::prefix('cart')->group(function() {
    Route::get('/step1', 'CartController@step1')->name('cart.step1');
    Route::get('/step2', 'CartController@step2')->name('cart.step2');
    Route::get('/step3/{code}', 'CartController@step3')->name('cart.step3');
    Route::get('/step4/{code}', 'CartController@step4')->name('cart.step4');
    Route::get('/confirm/{code}', 'CartController@confirm')->name('cart.confirm');

    Route::post('/add-item', 'CartController@addItem');
    Route::get('/remove-item', 'CartController@removeItem');
    Route::get('/update-item', 'CartController@updateItem');
    Route::get('/shipping-local', 'CartController@shippingLocal');
    Route::post('/create-order', 'CartController@createOrder');
    Route::post('/approve-order', 'CartController@approveOrder');
});

Route::group(['prefix' => 'claim', 'middleware' => 'auth'], function () {
    Route::get('/', 'ClaimController@index')->name('claim.frontend.index');
    Route::get('/{id}', 'ClaimController@view')->name('claim.frontend.view');
    Route::post('/create-conversation', 'ClaimController@createConversation');
    Route::post('/open', 'ClaimController@open');
});

Route::prefix('customer')->group(function() {
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('customer.login');
    Route::get('/forgot-password', 'Auth\LoginController@showForgotForm')->name('customer.forgot');
    Route::get('/register', 'Auth\RegisterController@showRegisterForm')->name('customer.register');

    Route::post('/login-submit', 'Auth\LoginController@loginSubmit')->name('customer.login.submit');
    Route::post('/login', 'Auth\LoginController@login');
    Route::post('/register', 'Auth\RegisterController@register')->name('customer.register.submit');
    Route::post('/forgot-password', 'Auth\ForgotPasswordController@forgot')->name('customer.forgot.submit');
    Route::post('/reset-password', 'Auth\ResetPasswordController@reset');
    Route::get('/logout', 'Auth\LoginController@logout')->name('customer.logout');
});

Route::group(['prefix' => 'admin/quotes', 'middleware' => 'auth:admin'], function() {
    Route::get('/', 'Admin\QuoteController@index')->name('quote.admin.index');
    Route::get('/{id}', 'Admin\QuoteController@show')->name('quote.admin.show');
    Route::put('/{id}/update', 'Admin\QuoteController@update')->name('quote.admin.update');
    Route::post('/{id}/cancel', 'Admin\QuoteController@cancel')->name('quote.admin.cancel');
    Route::get('/{id}/edit', 'Admin\QuoteController@edit')->name('quote.admin.edit');
});
Route::prefix('admin')->group(function() {
 Route::get('/password/forgot-pass', 'Admin\Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.forgot-pass');
 Route::post('/password/email', 'Admin\Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
 Route::post('/password/reset', 'Admin\Auth\AdminResetPasswordController@showLinkRequestForm')->name('admin.password.reset');
 Route::get('/password/expired', 'Admin\Auth\ExpiredPasswordController@expired')->name('admin.password.expired');
 Route::post('password/post_expired', 'Admin\Auth\ExpiredPasswordController@postExpired')->name('admin.password.post_expired');
 Route::get('/login', 'Admin\Auth\AdminLoginController@showLoginForm')->name('admin.login');
 Route::post('/login', 'Admin\Auth\AdminLoginController@login')->name('admin.login.submit');
 Route::post('/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout.submit');
 Route::get('/logout', 'Admin\Auth\AdminLoginController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin'], function () {
    // Profile thay đổi MK, thông tin
    Route::get('/profile/info', 'Admin\ProfileController@info')->name('admin.profile.info');
    Route::get('/profile/change-password', 'Admin\ProfileController@changePassword')->name('admin.profile.change-password');
    Route::get('/profile/passwordexpired', 'Admin\ProfileController@PasswordExpired')->name('admin.profile.passwordexpired');
    Route::put('/profile/info-update', 'Admin\ProfileController@infoUpdate')->name('admin.profile.info-update');
    Route::put('/profile/change-password-update', 'Admin\ProfileController@changePasswordUpdate')->name('admin.profile.change-password-update');
    // cập nhật check passwords
    Route::middleware(['password_expired'])->group(function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin.index');
    });
    Route::post('/config', 'Admin\ConfigController@config')->name('admin.config');
    Route::post('/pages/{id}/destroy', 'Admin\PagesController@destroy')->name('admin.page.destroy');

    Route::resource('product-groups', 'Admin\ProductGroupsController', [
        'except' => ['show'],
        'parameters' => [
            'product-groups' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-product-groups');

    Route::get('/checkAuth', function () {
        return true;
    });
    Route::resource('products', 'Admin\ProductsController', [
        'except' => ['show'],
        'parameters' => [
            'products' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-products');

    Route::resource('countries', 'Admin\CountriesController', [
        'except' => ['show'],
        'parameters' => [
            'countries' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-countries');

    Route::resource('provinces', 'Admin\ProvincesController', [
        'except' => ['show'],
        'parameters' => [
            'provinces' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-provinces');

    Route::resource('cities', 'Admin\CitiesController', [
        'except' => ['show'],
        'parameters' => [
            'cities' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-cities');

    Route::resource('wards', 'Admin\WardsController', [
        'except' => ['show'],
        'parameters' => [
            'wards' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-wards');

    Route::resource('pages', 'Admin\PagesController', [
        'except' => ['show'],
        'parameters' => [
            'pages' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-pages');

    Route::resource('banners', 'Admin\BannerController', [
        'except' => ['show'],
        'parameters' => [
            'banners' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-banners');

    Route::resource('news', 'Admin\NewsController', [
        'except' => ['show'],
        'parameters' => [
            'news' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-news');

    Route::resource('helps', 'Admin\HelpsController', [
        'except' => ['show'],
        'parameters' => [
            'helps' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-news');

    Route::put('/bulletin/{id}/updatepage', 'Admin\BulletinController@updatepage')->name('admin.bulletin.updatepage');;
    Route::resource('bulletin', 'Admin\BulletinController', [
        'parameters' => [
            'bulletin' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-bulletin');

    Route::resource('areas', 'Admin\AreasController', [
        'except' => ['show'],
        'parameters' => [

app/Mts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Enum\MtsTransactionTypeEnum;
use App\Enum\MtsStatusEnum;
use App\Country;
use App\Province;
use App\City;

class Mts extends Model
{
    //
    /**
     * Table to use
     */
    protected $table = 'tbl_mts';

    public function user() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
    
    public function customer() {
        return $this->belongsTo(Customer::class, 'customer_id', 'id');
    }

    public function receiver() {
        return $this->belongsTo(\App\Address::class, 'shipping_address_id', 'id');
    }

    public function agency() {
        return $this->belongsTo(Agency::class, 'agency_id', 'id');
    }

    public function currency() {
        return $this->belongsTo(Currency::class, 'currency_id', 'id');
    }
    
    public function sender_city() {
        return $this->belongsTo(City::class, 'sender_city_id', 'id');
    }
    
    public function sender_province() {
        return $this->belongsTo(Province::class, 'sender_province_id', 'id');
    }
    
    public function sender_country() {
        return $this->belongsTo(Country::class, 'sender_country_id', 'id');
    }
    
    public function receiver_city() {
        return $this->belongsTo(City::class, 'receiver_city_id', 'id');
    }
    
    public function receiver_province() {
        return $this->belongsTo(Province::class, 'receiver_province_id', 'id');
    }
    
    public function receiver_country() {
        return $this->belongsTo(Country::class, 'receiver_country_id', 'id');
    }
    
    public function getCreatedDateAttribute() {
        return $this->created_at->format(config('app.date_format'));
    }

    public function getSenderFullNameAttribute() {
        return "{$this->attributes['sender_last_name']} {$this->attributes['sender_middle_name']} {$this->attributes['sender_first_name']}";
    }
    public function getReceiveFullNameAttribute() {
        return "{$this->attributes['receiver_last_name']} {$this->attributes['receiver_middle_name']} {$this->attributes['receiver_first_name']}";
    }
    public function getTransactionTypeNameAttribute() {
        switch ($this->attributes['transaction_type']) {
            case MtsTransactionTypeEnum::TYPE_BANK:
                return __('mts.transaction_type_bank');
            case MtsTransactionTypeEnum::TYPE_ACCOUNT:
                return __('mts.transaction_type_account');
            default:
                return __('mts.transaction_type_home');
        }
    }
    
    public function getStatusNormalAttribute() {
        return MtsStatusEnum::NORMAL;
    }
    
    public function getStatusNameAttribute() {
        switch ($this->attributes['mts_status']) {
            case MtsStatusEnum::PROCESSING:
                return __('mts.status_processing');
            case MtsStatusEnum::CANCEL:
                return __('mts.status_cancel');
            case MtsStatusEnum::COMPLETE:
                return __('mts.status_complete');
            default:
                return __('mts.status_normal');
        }
    }

    public function getStatusLabelAttribute() {
        if ($this->attributes['mts_status'] == MtsStatusEnum::NORMAL) {
            return "badge";
        } else if ($this->attributes['mts_status'] == MtsStatusEnum::PROCESSING) {
            return "badge badge-warning";
        } else if ($this->attributes['mts_status'] == MtsStatusEnum::COMPLETE) {
            return "badge badge-success";
        } else if ($this->attributes['mts_status'] == MtsStatusEnum::CANCEL) {
            return "badge badge-danger";
        }
    }
}

resources/views/claim/index.blade.php
@extends('layouts.home.user', ['menu' => $menu])

@section('content')
<div class="panel panel-default user">
    <div class="panel-heading">
        {{ __('claim.list-claim') }}
    </div>
    <div class="panel-body">
        <div class="row form-group">
            <div class="col-sm-12">
                <form action="{{ route('claim.frontend.index') }}" method="get" role="form" class="form-inline">
                    <div class="form-group">
                        <input name="from_date" id="from_date" value="{{ request()->query('from_date')}}" class="form-control" type="text" style="width: 160px;" placeholder="{{ __('label.from_date') }}">
                    </div>
                    <div class="form-group">
                        <input name="to_date" id="to_date" value="{{ request()->query('to_date')}}" class="form-control" type="text" style="width: 160px;" placeholder="{{ __('label.to_date') }}">
                    </div>
                    <div class="form-group">
                        <input name="code" value="{{ request()->query('code')}}" class="form-control" type="text" style="width: 190px;" placeholder="{{ __('label.order_code') }}">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-white btn-single">
                            <i class="fa fa-search"></i> {{ __('label.find') }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <form id="shipment-package-form">
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th width="50">#</th>
                            <th width="150">{{ __('claim.request-code') }}</th>
                            <th width="160" class="text-center">{{ __('label.order_code') }}</th>
                            <th width="160" class="text-center">{{ __('claim.title') }}</th>
                            <th width="150" class="text-center">{{ __('label.create_time') }}</th>
                            <th width="120" class="text-center">{{ __('label.status') }}</th>
                            <th width="120">{{ __('label.action') }}</th>
                        </tr>
                    </thead>
                    <tbody id="shipment-package-items">
                        @if($claims->count() > 0)
                        <?php $no = 1; ?>
                        @foreach($claims as $claim)
                        <tr>
                            <td>
                                {{ $no }}
                            </td>
                            <td>
                                {{ $claim->code }}
                            </td>
                            <td class="text-center">{{ $claim->order->code }}</td>
                            <td class="text-center">{{ $claim->title }}</td>
                            <td class="text-center">{{ $claim->created_at }}</td>
                            <td class="text-center">
                                <span class="{{ $claim->status_label }}">{{ $claim->status_name }}</span>
                            </td>
                            <td>
                                <a href="{{ route('claim.frontend.view', $claim->id) }}" class="btn btn-xs btn-info">
                                    <i class="fa fa-eye"></i>
                                </a>
                            </td>
                        </tr>
                        <?php $no++; ?>
                        @endforeach
                        @else
                        <tr>
                            <td colspan="7">{{ __('label.no_records') }}</td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            <div class="paginate-single">
                {{ $claims->appends(request()->query())->links() }}
            </div>
        </form>
    </div>
</div>
@endsection

@section('footer')
<script>
    $(function () {
        $("#from_date").datepicker({dateFormat: "{{ config('app.date_format_js') }}"});
        $("#to_date").datepicker({dateFormat: "{{ config('app.date_format_js') }}"});
    });
</script>
@endsection

resources/views/claim/view.blade.php
@extends('layouts.home.user', ['menu' => $menu])

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            {{ __('claim.detail') }}: {{ $claim->code }}
        </div>
        <div class="row claim-container">
            <div class="col-sm-6">
                <div class="claim-content">
                    <h2>{{ $claim->title }}</h2>
                    <span>{{ __('label.order_code') }}: <label class="order-code">{{ $claim->order->code }}</label></span>
                    <span>{{ __('label.create_time') }}: <label>{{ $claim->created_at }}</label></span>
                    <span>{{ __('label.status') }}: <label>{{ $claim->status_name }}</label></span>
                    <span>{{ __('label.content') }}: <label class="claim-body">{{ $claim->title }}</label></span>
                </div>
            </div>
            <div class="col-sm-6 no-padding-left">
                <div class="claim-conversation">
                    <div class="claim-conversation-content" id="claim-conversation-content">
                        @if($claimConversations->count() > 0)
                        @foreach($claimConversations as $claimConversation)
                        @if(!empty($claimConversation->user_id))
                        <div class="user-conversation">
                            <label>{{ $claimConversation->content }}</label>
                            <span class="claim-conversation-user">{{ $claimConversation->user->username }}</span>
                            <span class="claim-conversation-time">{{ $claimConversation->created_at }}</span>
                        </div>
                        @else
                        <div class="customer-conversation">
                            <label>{{ $claimConversation->content }}</label>
                            <span class="claim-conversation-time">{{ $claimConversation->created_at }}</span>
                        </div>
                        @endif
                        @endforeach
                        @endif
                    </div>
                    
                    @if($claim->status != 3 && $claim->status != 4)
                    <div class="claim-conversation-form">
                        <form id="claim-comment-form">
                            <textarea name="comment"></textarea>
                            <input type="hidden" name="id" value="{{$claim->id}}">
                            {{ csrf_field() }}
                        </form>
                        
                        <button type="button" onclick="claim.addConversation();">{{ __('label.send') }}</button>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer')
<script src="/js/home/claim.js"></script>
@endsection