routes/web.php
    Route::get('/transport-agency-order', 'Admin\ApiController@transportAgencyOrder');
    Route::get('/transport-customer-quote', 'Admin\ApiController@transportCustomerQuote');
    Route::get('/transport-customer-order', 'Admin\ApiController@transportCustomerOrder');

    Route::get('/yhl-agency-order', 'Admin\ApiController@yhlAgencyOrder');
    Route::get('/yhl-customer-order', 'Admin\ApiController@yhlCustomerOrder');

    Route::get('/express-agency-order', 'Admin\ApiController@expressAgencyOrder');
    Route::get('/express-customer-order', 'Admin\ApiController@expressCustomerOrder');

    Route::get('/mts-agency-order', 'Admin\ApiController@mtsAgencyOrder');
    Route::get('/mts-customer-order', 'Admin\ApiController@mtsCustomerOrder');

    Route::get('/quote-shop', 'Admin\ApiController@quoteShop');
});
Route::group(['prefix' => 'api', 'middleware' => ['web']], function () {
    Route::get('/warehouses', 'ApiController@getWarehouses');
    Route::get('/countries', 'ApiController@getCountries');
    Route::get('/provinces', 'ApiController@getProvinces')->name('api.provinces');
    Route::get('/cities', 'ApiController@getCities')->name('api.cities');
    Route::get('/wards', 'ApiController@getWards')->name('api.wards');;
    Route::get('/products', 'ApiController@getProducts');
    Route::get('/dim-types', 'ApiController@getDimTypes');
    Route::get('/payment-methods', 'ApiController@getPaymentMethods');
    Route::get('/address', 'ApiController@getAddress');
    Route::post('/coupon', 'ApiController@couponAmount');
    Route::post('/used-coupon', 'ApiController@usedCoupon');
    Route::post('/remove-coupon', 'ApiController@removedCoupon');
    Route::get('/currencies', 'ApiController@getCurrencies');
});

Route::group(['prefix' => 'files'], function () {
    Route::post('/upload', 'FilesController@upload')->name('files.upload');
});

Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('customer.verify');
Route::get('/reset-password/{token}', 'Auth\ResetPasswordController@showResetForm')->name('customer.reset');

Route::group(['prefix' => 'agency'], function() {
    Route::get('/', 'AgencyController@index')->name('agency.index');
});

Route::group(['prefix' => 'quotes', 'middleware' => 'auth'], function() {
    Route::get('/', 'QuoteController@index')->name('quote.frontend.index');
    Route::get('/create', 'QuoteController@create')->name('quote.frontend.create');
    Route::post('/store', 'QuoteController@store');
    Route::get('/{id}', 'QuoteController@show')->name('quote.frontend.show');
    Route::put('/{id}/update', 'QuoteController@update')->name('quote.frontend.update');
    Route::get('/{id}/edit', 'QuoteController@edit')->name('quote.frontend.edit');
});

Route::group(['prefix' => 'transports', 'middleware' => 'auth'], function() {
    Route::get('/', 'TransportController@index')->name('transport.frontend.index');
    Route::get('/create', 'TransportController@create')->name('transport.frontend.create');
    Route::post('/store', 'TransportController@store');
    Route::post('/get-quote', 'TransportController@getQuotes');
    Route::get('/{id}', 'TransportController@show')->name('transport.frontend.show');
    Route::put('/{id}/update', 'TransportController@update')->name('transport.frontend.update');
    Route::get('/{id}/edit', 'TransportController@edit')->name('transport.frontend.edit');
    Route::get('/{id}/print_bill', 'TransportController@printBill')->name('transport.frontend.print');
    Route::get('/{id}/get-pdf', 'TransportController@getPdf')->name('transport.frontend.pdf');
    Route::get('/{id}/view-history-eshipper', 'TransportController@viewHistoryEshipper');
});

Route::group(['prefix' => 'transport/orders', 'middleware' => 'auth'], function() {
    Route::get('/', 'TransportOrderController@index')->name('transport.order.list');
    Route::get('/{id}', 'TransportOrderController@show')->name('transport.order.show');
    Route::put('/{id}/update', 'TransportOrderController@update')->name('transport.order.update');
    Route::get('/{id}/edit', 'TransportOrderController@edit')->name('transport.order.edit');
    Route::get('/{id}/print_bill', 'TransportOrderController@printBill')->name('transport.order.print');
     Route::get('/{id}/print_bills', 'TransportOrderController@printBills')->name('transport.order.prints');
    Route::get('/{id}/view-history', 'TransportOrderController@viewHistory');
     Route::get('/{id}/get-pdf', 'TransportOrderController@getPdf')->name('transport.order.pdf');
});

Route::group(['prefix' => 'yhl', 'middleware' => 'auth'], function () {
    Route::get('/', 'YhlController@index')->name('yhl.frontend.index');
});

Route::group(['prefix' => 'mts', 'middleware' => 'auth'], function () {
    Route::get('/', 'MtsController@index')->name('mts.frontend.index');
    Route::get('/create', 'MtsController@create')->name('mts.frontend.create');
    Route::post('/store', 'MtsController@store');
    Route::get('/{id}', 'MtsController@show')->name('mts.frontend.show');
    Route::put('/{id}/update', 'MtsController@update')->name('mts.frontend.update');
    Route::get('/{id}/edit', 'MtsController@edit')->name('mts.frontend.edit');
});

Route::group(['prefix' => 'profile', 'middleware' => 'auth'], function () {
    Route::get('/', 'CustomerController@index')->name('profile.index');
    Route::get('/change-password', 'CustomerController@changePassword')->name('profile.changepass');
    Route::get('/address', 'CustomerController@address')->name('profile.address');
    Route::get('/point', 'CustomerController@point')->name('profile.point');
    Route::get('/coupon', 'CustomerController@coupon')->name('profile.coupon');
    Route::get('/get-coupon-code', 'CustomerController@getCouponCode');
    Route::get('/{id}/address-edit', 'CustomerController@addressEdit')->name('profile.address_edit');
    Route::put('/{id}/address-update', 'CustomerController@addressUpdate')->name('profile.address_update');
    Route::get('/address-create', 'CustomerController@addressCreate')->name('profile.address_create');
    Route::put('/address-store', 'CustomerController@addressStore')->name('profile.address_store');
    Route::get('/{id}/address-destroy', 'CustomerController@addressDestroy')->name('profile.address_destroy');
    Route::post('/update', 'CustomerController@update')->name('profile.update');
    Route::post('/update-change-password', 'CustomerController@updateChangePassword')->name('profile.update_changepass');
});

Route::prefix('product')->group(function() {
    Route::get('/', 'ProductController@index')->name('product.index');
    Route::get('/category/{id}', 'ProductController@category')->name('product.category');
    Route::get('/detail/{name}/{id}', 'ProductController@detail')->name('product.detail');
});

Route::prefix('news')->group(function() {
    Route::get('/', 'NewsController@index')->name('news.index');
    Route::get('/{slug}', 'NewsController@detail')->name('news.detail');
});

Route::prefix('helps')->group(function() {
    Route::get('/', 'HelpsController@index')->name('helps.index');
    Route::get('/{slug}', 'HelpsController@detail')->name('helps.detail');
});

Route::prefix('cart')->group(function() {
    Route::get('/step1', 'CartController@step1')->name('cart.step1');
    Route::get('/step2', 'CartController@step2')->name('cart.step2');
    Route::get('/step3/{code}', 'CartController@step3')->name('cart.step3');
    Route::get('/step4/{code}', 'CartController@step4')->name('cart.step4');
    Route::get('/confirm/{code}', 'CartController@confirm')->name('cart.confirm');

    Route::post('/add-item', 'CartController@addItem');
    Route::get('/remove-item', 'CartController@removeItem');
    Route::get('/update-item', 'CartController@updateItem');
    Route::get('/shipping-local', 'CartController@shippingLocal');
    Route::post('/create-order', 'CartController@createOrder');
    Route::post('/approve-order', 'CartController@approveOrder');
});

Route::group(['prefix' => 'claim', 'middleware' => 'auth'], function () {
    Route::get('/', 'ClaimController@index')->name('claim.frontend.index');
    Route::get('/{id}', 'ClaimController@view')->name('claim.frontend.view');
    Route::post('/create-conversation', 'ClaimController@createConversation');
    Route::post('/open', 'ClaimController@open');
});

Route::prefix('customer')->group(function() {
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('customer.login');
    Route::get('/forgot-password', 'Auth\LoginController@showForgotForm')->name('customer.forgot');
    Route::get('/register', 'Auth\RegisterController@showRegisterForm')->name('customer.register');

    Route::post('/login-submit', 'Auth\LoginController@loginSubmit')->name('customer.login.submit');
    Route::post('/login', 'Auth\LoginController@login');
    Route::post('/register', 'Auth\RegisterController@register')->name('customer.register.submit');
    Route::post('/forgot-password', 'Auth\ForgotPasswordController@forgot')->name('customer.forgot.submit');
    Route::post('/reset-password', 'Auth\ResetPasswordController@reset');
    Route::get('/logout', 'Auth\LoginController@logout')->name('customer.logout');
});

Route::group(['prefix' => 'admin/quotes', 'middleware' => 'auth:admin'], function() {
    Route::get('/', 'Admin\QuoteController@index')->name('quote.admin.index');
    Route::get('/{id}', 'Admin\QuoteController@show')->name('quote.admin.show');
    Route::put('/{id}/update', 'Admin\QuoteController@update')->name('quote.admin.update');
    Route::post('/{id}/cancel', 'Admin\QuoteController@cancel')->name('quote.admin.cancel');
    Route::get('/{id}/edit', 'Admin\QuoteController@edit')->name('quote.admin.edit');
});
Route::prefix('admin')->group(function() {
 Route::get('/password/forgot-pass', 'Admin\Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.forgot-pass');

app/Mts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Enum\MtsTransactionTypeEnum;
use App\Enum\MtsStatusEnum;
use App\Country;
use App\Province;
use App\City;

class Mts extends Model
{
    //
    /**
     * Table to use
     */
    protected $table = 'tbl_mts';

    public function user() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
    
    public function customer() {
        return $this->belongsTo(Customer::class, 'customer_id', 'id');
    }

    public function receiver() {
        return $this->belongsTo(\App\Address::class, 'shipping_address_id', 'id');
    }

    public function agency() {
        return $this->belongsTo(Agency::class, 'agency_id', 'id');
    }

    public function currency() {
        return $this->belongsTo(Currency::class, 'currency_id', 'id');
    }
    
    public function sender_city() {
        return $this->belongsTo(City::class, 'sender_city_id', 'id');
    }
    
    public function sender_province() {
        return $this->belongsTo(Province::class, 'sender_province_id', 'id');
    }
    
    public function sender_country() {
        return $this->belongsTo(Country::class, 'sender_country_id', 'id');
    }
    
    public function receiver_city() {
        return $this->belongsTo(City::class, 'receiver_city_id', 'id');
    }
    
    public function receiver_province() {
        return $this->belongsTo(Province::class, 'receiver_province_id', 'id');
    }
    
    public function receiver_country() {
        return $this->belongsTo(Country::class, 'receiver_country_id', 'id');
    }
    
    public function getCreatedDateAttribute() {
        return $this->created_at->format(config('app.date_format'));
    }

    public function getSenderFullNameAttribute() {
        return "{$this->attributes['sender_last_name']} {$this->attributes['sender_middle_name']} {$this->attributes['sender_first_name']}";
    }
    public function getReceiveFullNameAttribute() {
        return "{$this->attributes['receiver_last_name']} {$this->attributes['receiver_middle_name']} {$this->attributes['receiver_first_name']}";
    }
    public function getTransactionTypeNameAttribute() {
        switch ($this->attributes['transaction_type']) {
            case MtsTransactionTypeEnum::TYPE_BANK:
                return __('mts.transaction_type_bank');
            case MtsTransactionTypeEnum::TYPE_ACCOUNT:
                return __('mts.transaction_type_account');
            default:
                return __('mts.transaction_type_home');
        }
    }
    
    public function getStatusNormalAttribute() {
        return MtsStatusEnum::NORMAL;
    }
    
    public function getStatusNameAttribute() {
        switch ($this->attributes['mts_status']) {
            case MtsStatusEnum::PROCESSING:
                return __('mts.status_processing');
            case MtsStatusEnum::CANCEL:
                return __('mts.status_cancel');
            case MtsStatusEnum::COMPLETE:
                return __('mts.status_complete');
            default:
                return __('mts.status_normal');
        }
    }

    public function getStatusLabelAttribute() {
        if ($this->attributes['mts_status'] == MtsStatusEnum::NORMAL) {
            return "badge";
        } else if ($this->attributes['mts_status'] == MtsStatusEnum::PROCESSING) {
            return "badge badge-warning";
        } else if ($this->attributes['mts_status'] == MtsStatusEnum::COMPLETE) {
            return "badge badge-success";
        } else if ($this->attributes['mts_status'] == MtsStatusEnum::CANCEL) {
            return "badge badge-danger";
        }
    }
}

resources/views/prints/print_invoice100x75.blade.php
@extends('layouts.admin.print2021')
@section('header')
  <style>
    /* kich thuoc trang giay */
    @page {
      size: 120mm 90mm;
      margin-top: 1mm;
    }

    /* nội dung tren web va noi dung in*/
    .page {
      width: 118mm;
      height: 88mm;
    }

  </style>
@endsection
@section('body')
  @foreach ($orders as $order)
    <div id="print">
      <center>
        <div class="page">
          <div class="subpage">
            <table border="1px" cellspacing="0px" width="100%" style="font-size:10pt; font-weight: bold;">
              <tbody>
                <tr>
                  <td width="30%">Mã phiếu #:</td>
                  <td style="font-size:150%;">{{ $order->code }}</td>
                </tr>
                <tr>
                  <td>NGƯỜI GỬI:</td>
                  <td>{{ $order->sender_full_name }}</td>
                </tr>
                <tr>
                  <td>NGƯỜI NHẬN:</td>
                  <td>{{ $order->receive_full_name }}</td>
                </tr>
                <tr>
                  <td>ĐIỆN THOẠI:</td>
                  <td> {{ $order->receiver_phone }}
                    @if (!empty($order->receiver_cellphone))
                      , {{ $order->receiver_cellphone }}
                    @endif
                  </td>
                </tr>
                <tr>
                  <td> ĐỊA CHỈ:</td>
                  <td> {{ $order->receiver_address }} {{ $order->receiver_address_2 }} ,
                    @if (!empty($order->receiver_ward->name))
                      {{ $order->receiver_ward->name }} @endif
                    , {{ $order->receiver_city->name }},
                    {{ $order->receiver_province->name }}, {{ $order->receiver_country->name }}
                  </td>
                </tr>
                <tr style="text-align: center;">
                  <td colspan="2">
                    <svg id="barcode{{ $order->code }}"></svg>
                  </td>
                </tr>
                <tr>
                  <td colspan="2">
                    <div style="font-size:6pt;">
                      <b>Lưu ý:</b> Người nhận có thể từ chối hoặc yêu cầu cùng kiểm hàng nếu phát
                      hiện kiện hàng không còn nguyên đai, nguyên kiện. Công ty sẽ không chịu
                      trách nhiệm nội dung hàng bên trong kiện nếu đã có chữ ký nhận hàng. Vui lòng liên hệ 1900-055-509 khi cần thêm thông tin.
                    </div>
                  </td>
                </tr>
                <tr style="text-align: right;">
                  <td colspan="2">
                    @php
                      $dangers = strrev(decbin($order->danger_type));
                    @endphp
                    @for ($i = strlen($dangers)-1; $i >= 0; $i--)
                      @if ($i === 2 && $dangers[$i])
                      <i class="fas fa-notes-medical" style="font-size:42px"></i>
                      @endif
                      @if ($i === 1 && $dangers[$i])
                        <i class="fa fa-tint" style="font-size:42px"></i>
                      @endif
                      @if ($i === 0 && $dangers[$i])
                        <i class="fa fa-battery-empty" style="font-size:42px"></i>
                      @endif
                    @endfor
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

        </div>
        <span id="ctl01_lbthongbao">
          <script language="javascript">
            window.print();
          </script>
        </span>
      </center>
    </div>
    <span id="lbthongbao"></span>
    <script>
      JsBarcode("#barcode{{ $order->code }}", "{{ $order->code }}", {
        format: "CODE128",
        displayValue: false,
        fontSize: 12,
        height: 50,
        width: 2
      });
    </script>
  @endforeach
@endsection