routes/web.php
        'except' => ['show'],
        'parameters' => [
            'provinces' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-provinces');

    Route::resource('cities', 'Admin\CitiesController', [
        'except' => ['show'],
        'parameters' => [
            'cities' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-cities');

    Route::resource('wards', 'Admin\WardsController', [
        'except' => ['show'],
        'parameters' => [
            'wards' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-wards');

    Route::resource('pages', 'Admin\PagesController', [
        'except' => ['show'],
        'parameters' => [
            'pages' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-pages');

    Route::resource('banners', 'Admin\BannerController', [
        'except' => ['show'],
        'parameters' => [
            'banners' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-banners');

    Route::resource('news', 'Admin\NewsController', [
        'except' => ['show'],
        'parameters' => [
            'news' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-news');

    Route::resource('helps', 'Admin\HelpsController', [
        'except' => ['show'],
        'parameters' => [
            'helps' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-news');

    Route::put('/bulletin/{id}/updatepage', 'Admin\BulletinController@updatepage')->name('admin.bulletin.updatepage');;
    Route::resource('bulletin', 'Admin\BulletinController', [
        'parameters' => [
            'bulletin' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-bulletin');

    Route::resource('areas', 'Admin\AreasController', [
        'except' => ['show'],
        'parameters' => [
            'areas' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-areas');

    Route::resource('point-converts', 'Admin\PointConvertController', [
        'except' => ['show'],
        'parameters' => [
            'point-converts' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-point-converts');

    Route::resource('point-configs', 'Admin\PointConfigController', [
        'except' => ['show'],
        'parameters' => [
            'point-configs' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-point-configs');

    Route::resource('dimensions', 'Admin\DimensionUnitController', [
        'except' => ['show'],
        'parameters' => [
            'dimensions' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-dimensions');

    Route::resource('measures', 'Admin\MessureUnitController', [
        'except' => ['show'],
        'parameters' => [
            'measures' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-measures');
    Route::get('warehouses/{id}/list_product', 'Admin\WarehouseController@list_product')->name('warehouses.list_product');
    Route::resource('warehouses', 'Admin\WarehouseController', [
        'except' => ['show'],
        'parameters' => [
            'warehouses' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-warehouses');
    Route::resource('weights', 'Admin\WeightUnitController', [
        'except' => ['show'],
        'parameters' => [
            'weights' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-weights');

    Route::resource('shipping-methods', 'Admin\ShippingMethodController', [
        'except' => ['show'],
        'parameters' => [
            'shipping-methods' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-shipping-methods');

    Route::resource('shipping-providers', 'Admin\ShippingProviderController', [
        'except' => ['show'],
        'parameters' => [
            'shipping-providers' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-shipping-providers');
    // them ngay 15-07-2021
    Route::resource('shipping-method-providers', 'Admin\ShippingMethodProviderController', [
        'except' => ['show'],
        'parameters' => [
            'shipping-method-providers' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-shipping-providers');
    // het them ngay 15-07-2021
    Route::resource('payment-methods', 'Admin\PaymentMethodController', [
        'except' => ['show'],
        'parameters' => [
            'payment-methods' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-payment-methods');

    Route::get('/vnptconfirm', 'Admin\Vnptconfirm@index')->name('admin.vnptconfirm.index');
    Route::post('/vnptconfirm', 'Admin\Vnptconfirm@store')->name('admin.vnptconfirm');
    Route::post('/extent/approve', 'Admin\ExtentController@approve');
    Route::post('/extent/payment', 'Admin\ExtentController@payment');
    Route::post('/extent/cancel', 'Admin\ExtentController@cancel');
    Route::get('/extent', 'Admin\ExtentController@index')->name('admin.extent.index');
    Route::get('/extent/exportExcel', 'Admin\ExtentController@exportExcel')->name('admin.extent.exportExcel');
    Route::get('/extrafee/{orderid}/list', 'Admin\ExtentController@extrafee')->name('admin.extent.extrafee');

    Route::resource('extent', 'Admin\ExtentController', [
        'except' => ['show'],
        'parameters' => [
            'extent' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-extent');

    Route::get('/claim/view/{id}', 'Admin\ClaimController@view')->name('admin.claim.view');
    Route::post('/claim/create-conversation', 'Admin\ClaimController@createConversation');
    Route::post('/claim/complete', 'Admin\ClaimController@complete');
    Route::get('/claim/contact', 'Admin\ClaimController@contact')->name('admin.claim.contact');
    Route::get('/claim/contact/{id}/delete', 'Admin\ClaimController@delete')->name('admin.claim.delete');
    Route::resource('claim', 'Admin\ClaimController', [
        'except' => ['show'],
        'parameters' => [
            'claim' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-claim');

    Route::get('/receipts/excel', 'Admin\ReceiptController@exportExcel')->name('admin.receipts.excel');
    Route::resource('receipts', 'Admin\ReceiptController', [
        'except' => ['show'],
        'parameters' => [
            'receipts' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts');

    Route::post('/receipt-orders/add-items', 'Admin\ReceiptOrdersController@addItems')->name('admin.receipt-orders.add-items');
    Route::post('/receipt-orders/remove-item', 'Admin\ReceiptOrdersController@removeItem')->name('admin.receipt-orders.remove-item');
    Route::post('/receipt-orders/paid-voucher', 'Admin\ReceiptOrdersController@paidVoucher')->name('admin.receipt-orders.paid-voucher');
    Route::get('/receipt-orders/excel-item/{id}', 'Admin\ReceiptOrdersController@exportExcelItem')->name('admin.receipt-orders.excel-item');
    Route::get('/receipt-orders/excel', 'Admin\ReceiptOrdersController@exportExcel')->name('admin.receipt-orders.excel');
    Route::get('/receipt-orders/{id}/print', 'Admin\ReceiptOrdersController@printItem')->name('admin.receipt-orders.print-item');
    Route::resource('receipt-orders', 'Admin\ReceiptOrdersController', [
        'except' => ['show'],
        'parameters' => [
            'receipt-orders' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts-order');

    Route::post('/receipt-mts/add-items', 'Admin\ReceiptMtsController@addItems')->name('admin.receipt-mts.add-items');
    Route::post('/receipt-mts/remove-item', 'Admin\ReceiptMtsController@removeItem')->name('admin.receipt-mts.remove-item');
    Route::post('/receipt-mts/paid-voucher', 'Admin\ReceiptMtsController@paidVoucher')->name('admin.receipt-mts.paid-voucher');
    Route::get('/receipt-mts/excel-item/{id}', 'Admin\ReceiptMtsController@exportExcelItem')->name('admin.receipt-mts.excel-item');
    Route::get('/receipt-mts/excel', 'Admin\ReceiptMtsController@exportExcel')->name('admin.receipt-mts.excel');
    Route::get('/receipt-mts/{id}/print', 'Admin\ReceiptMtsController@printItem')->name('admin.receipt-mts.print-item');
    Route::resource('receipt-mts', 'Admin\ReceiptMtsController', [
        'except' => ['show'],
        'parameters' => [
            'receipt-mts' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts-mts');

    Route::post('/receipt-extra/add-items', 'Admin\ReceiptExtraController@addItems')->name('admin.receipt-extra.add-items');
    Route::post('/receipt-extra/remove-item', 'Admin\ReceiptExtraController@removeItem')->name('admin.receipt-extra.remove-item');
    Route::post('/receipt-extra/paid-voucher', 'Admin\ReceiptExtraController@paidVoucher')->name('admin.receipt-extra.paid-voucher');
    Route::get('/receipt-extra/excel-item/{id}', 'Admin\ReceiptExtraController@exportExcelItem')->name('admin.receipt-extra.excel-item');
    Route::get('/receipt-extra/excel', 'Admin\ReceiptExtraController@exportExcel')->name('admin.receipt-extra.excel');
    Route::get('/receipt-extra/{id}/print', 'Admin\ReceiptExtraController@printItem')->name('admin.receipt-extra.print-item');
    Route::resource('receipt-extra', 'Admin\ReceiptExtraController', [
        'except' => ['show'],
        'parameters' => [
            'receipt-extra' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-receipts-extra');

    Route::resource('customer-groups', 'Admin\CustomerGroupsController', [
        'except' => ['show'],
        'parameters' => [
            'customer-groups' => 'id'
        ],
        'as' => 'admin'
    ])->middleware('can:manage-customer-groups');

    Route::get('/customers/points', 'Admin\CustomersController@points')->name('admin.customers.points');

resources/views/admin/weights/create.blade.php
@extends('layouts.admin.index', ['menu' => $menu])

@section('body')
    <div class="panel panel-default">
        <div class="panel-heading">
            {{ __('dimension.create') }}
        </div>
        <div class="panel-body">
            <form action="{{ route('admin.weights.store') }}" method="post" role="form" class="form-horizontal">
                <div class="row">
                    <div class="col-sm-6">
                        @php $field = 'code'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('dimension.code') }}<i class="text-danger">*</i>
                            </label>

                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>

                        @php $field = 'name'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('dimension.name') }}<i class="text-danger">*</i>
                            </label>

                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                        @php $field = 'radio'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('weight.radio') }}
                            </label>

                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control"
                                       value="{{ old($field) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        @php $field = 'display_order'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('weight.display_order') }}
                            </label>

                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                        @php $field = 'is_default'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('dimension.is_default') }}
                            </label>
                            <div class="col-sm-9">
                                <select name="{{ $field }}" id="{{ $field }}" class="form-control">
                                    <option value="2">
                                        {{ __('label.no') }}
                                    </option>
                                    <option value="1">
                                        {{ __('label.yes') }}
                                    </option>
                                </select>
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12 text-right">
                            <a href="{{ route('admin.weights.index') }}" class="btn btn-white">
                                {{ __('label.cancel') }}
                            </a>
                            <button type="submit" class="btn btn-info disabled-submit">
                                <i class="fa fa-check"></i> {{ __('label.save') }}
                            </button>
                        </div>
                    </div>
                </div>
                {{ csrf_field() }}
            </form>
        </div>
    </div>
@endsection

resources/views/admin/weights/edit.blade.php
@extends('layouts.admin.index', ['menu' => $menu])

@section('body')
    <div class="panel panel-default">
        <div class="panel-heading">
            {{ __('weight.edit') }}
        </div>
        <div class="panel-body">
            <form action="{{ route('admin.weights.update', $weights->id) }}" method="post" role="form" class="form-horizontal">
                <div class="row">
                    <div class="col-sm-6">
                        @php $field = 'code'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('weight.code') }}<i class="text-danger">*</i>
                            </label>
                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field, $weights->{$field}) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>

                        @php $field = 'name'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('weight.name') }}<i class="text-danger">*</i>
                            </label>
                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field, $weights->{$field}) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                        @php $field = 'radio'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('weight.radio') }}
                            </label>

                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control"
                                       value="{{ old($field, $weights->{$field}) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6">
                        @php $field = 'display_order'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('weight.display_order') }}
                            </label>

                            <div class="col-sm-9">
                                <input type="text" name="{{ $field }}" class="form-control" value="{{ old($field, $weights->{$field}) }}">
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                        @php $field = 'is_default'; @endphp
                        <div class="form-group{{ $errors->has($field) ? ' validate-has-error' : '' }}">
                            <label for="{{ $field }}" class="control-label col-sm-3">
                                {{ __('dimension.is_default') }}
                            </label>
                            <div class="col-sm-9">
                                <select name="{{ $field }}" id="{{ $field }}" class="form-control">
                                    <option value="2" @if(2 == old($field, $weights->{$field})) selected="selected"@endif>
                                        {{ __('label.no') }}
                                    </option>
                                    <option value="1" @if(1 == old($field, $weights->{$field})) selected="selected"@endif>
                                        {{ __('label.yes') }}
                                    </option>
                                </select>
                                @if($errors->has($field))
                                    <span class="validate-has-error">{{ $errors->first($field) }}</span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12 text-right">
                            <a href="{{ route('admin.weights.index') }}" class="btn btn-white">
                                {{ __('label.cancel') }}
                            </a>
                            <button type="submit" class="btn btn-info disabled-submit">
                                <i class="fa fa-check"></i> {{ __('label.update') }}
                            </button>
                        </div>
                    </div>
                </div>
                {{ method_field('PUT') }}
                {{ csrf_field() }}
            </form>
        </div>
    </div>
@endsection

resources/views/admin/weights/index.blade.php
@extends('layouts.admin.index', ['menu' => $menu])

@section('body')
  <div class="panel panel-default">
    <div class="panel-heading">
      {{ __('weight.weight_unit') }}
    </div>
    <div class="panel-body">
      <div class="row form-group">
        <div class="col-sm-1">
          <a href="{{ route('admin.weights.create') }}" class="btn btn-success">
            <i class="fa fa-plus-circle"></i> {{ __('label.add') }}
          </a>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th>{{ __('weight.code') }}</th>
            <th>{{ __('weight.name') }}</th>
            <th width="30%">{{ __('weight.is_default') }}</th>
            <th width="30%">{{ __('weight.radio') }}</th>
            <th>{{ __('label.action') }}</th>
          </tr>
          </thead>
          <tbody>
          @if($weights->count() > 0)
            @foreach($weights as $weight)
              <tr>
                <td>{{ $weight->code }}</td>
                <td>{{ $weight->name }}</td>
                <td>{{ $weight->is_default_name }}</td>
                <td>{{ $weight->radio }}</td>
                <td>
                  <a href="{{ route('admin.weights.edit', $weight->id) }}" class="btn btn-xs btn-warning">
                    <i class="fa fa-edit"></i>
                  </a>
                  <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal-delete-{{ $weight->id }}">
                    <i class="fas fa-trash"></i>
                  </button>
                  <div class="modal fade" id="modal-delete-{{ $weight->id }}">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <form action="{{ route('admin.weights.destroy', $weight->id) }}" method="post">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">{{ __('label.confirm_delete') }}</h4>
                          </div>
                          <div class="modal-body">
                            {!! __('label.confirm_delete_msg') !!}
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-white" data-dismiss="modal">{{ __('label.cancel') }}</button>
                            <button type="submit" class="btn btn-danger disabled-submit">
                              <i class="fas fa-trash"></i> {{ __('label.delete') }}
                            </button>
                          </div>
                          {{ csrf_field() }}
                          {{ method_field('delete') }}
                        </form>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            @endforeach
          @else
            <tr>
              <td colspan="4">{{ __('label.no_records') }}</td>
            </tr>
          @endif
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection